
version: "3.9"
services:
  app1:
    build: ./backend
    container_name: brokerx_go_app1
    environment:
      - PORT=8000
      - JWT_SECRET=devsecret
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/brokerx?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on: [postgres, redis]

  app2:
    build: ./backend
    container_name: brokerx_go_app2
    environment:
      - PORT=8000
      - JWT_SECRET=devsecret
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/brokerx?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on: [postgres, redis]

  postgres:
    image: postgres:16
    container_name: brokerx_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brokerx
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: brokerx_redis
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    container_name: brokerx_frontend

  nginx:
    image: nginx:alpine
    container_name: brokerx_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on: [app1, app2, frontend]

  kong:
    image: kong:3.6
    container_name: brokerx_kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong/kong.yml:/kong/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on: [nginx]

  prometheus:
    image: prom/prometheus:latest
    container_name: brokerx_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on: [app1, app2]

  grafana:
    image: grafana/grafana:latest
    container_name: brokerx_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on: [prometheus]
